name: Unit testing

on:
  pull_request:
    branches: ['main', 'production']

jobs:
  build:
    name: Build for macos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.9'
      - name: Installing dependencies
        run: pip3 install -r requirements.txt
      - name: Test
        shell: bash --noprofile --norc -eo pipefail {0}
        run: pytest
